Description: "Creates a Linux Media Server."
Mappings:
  Images:
    us-east-1:
      Id: "ami-04505e74c0741db8d"
    us-east-2:
      Id: "ami-0fb653ca2d3203ac1"
    us-west-1:
      Id: "ami-01f87c43e618bf8f0"
    us-west-2:
      Id: "ami-017fecd1353bcc96e"
Parameters:
  VpcId:
    Type: String
  MediaServerName:
    Type: String
    Default: media-server
Resources:
  MediaServerKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: media-server-keypair
  MediaServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security Group for AMIs
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 1935
          ToPort: 1935
          CidrIp: 0.0.0.0/0
  MediaServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - Images
        - !Ref AWS::Region
        - Id
      InstanceType: "t3.large"
      KeyName: !Ref MediaServerKeyPair
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 10
            DeleteOnTermination: true
      SecurityGroupIds:
        - !Ref MediaServerSecurityGroup
      Tags:
        - Key: "Name"
          Value: !Ref MediaServerName
Outputs:
  InstanceId:
    Value: !Ref MediaServerInstance
  PublicDnsName:
    Value: !GetAtt MediaServerInstance.PublicDnsName
